# Generated by Django 4.1.2 on 2022-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_widget_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='author_username',
            new_name='author',
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[
                ('line', 'Line'), ('bar', 'Bar'),
                ('bubbleChart', 'Bubble Chart'),
                ('pieChart', 'Pie Chart'), ('number', 'Number'),
                ('column', 'Column'), ('heatMap', 'Heat Map'),
                ('grid', 'Grid'), ('range', 'Range'),
                ('unspecifiedType', 'Unspecified Type')],
                                   default='unspecifiedType',
                                   max_length=32),
        ),
    ]
